# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Setup(object):
    def setupUi(self, Setup):
        Setup.setObjectName("Setup")
        Setup.resize(680, 500)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        Setup.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Setup)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 50, 511, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 130, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 170, 191, 151))
        self.groupBox.setObjectName("groupBox")
        self.device = QtWidgets.QComboBox(self.groupBox)
        self.device.setGeometry(QtCore.QRect(10, 30, 121, 22))
        self.device.setObjectName("device")
        self.device.addItem("")
        self.device.addItem("")
        self.device.addItem("")
        self.device.addItem("")
        self.check1 = QtWidgets.QPushButton(self.groupBox)
        self.check1.setGeometry(QtCore.QRect(10, 80, 121, 28))
        self.check1.setObjectName("check1")
        self.button2 = QtWidgets.QGroupBox(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(400, 170, 191, 151))
        self.button2.setObjectName("button2")
        self.input = QtWidgets.QComboBox(self.button2)
        self.input.setGeometry(QtCore.QRect(10, 30, 121, 22))
        self.input.setObjectName("input")
        self.input.addItem("")
        self.input.addItem("")
        self.input.addItem("")
        self.input.addItem("")
        self.check2 = QtWidgets.QPushButton(self.button2)
        self.check2.setGeometry(QtCore.QRect(10, 80, 121, 28))
        self.check2.setObjectName("check2")
        Setup.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Setup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 23))
        self.menubar.setObjectName("menubar")
        Setup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Setup)
        self.statusbar.setObjectName("statusbar")
        Setup.setStatusBar(self.statusbar)

        self.retranslateUi(Setup)
        QtCore.QMetaObject.connectSlotsByName(Setup)
        # kiem tra trang thai
        self.check1.clicked.connect(self.checkfunction)
        self.check2.clicked.connect(self.checkfunction)

    def retranslateUi(self, Setup):
        _translate = QtCore.QCoreApplication.translate
        Setup.setWindowTitle(_translate("Setup", "MainWindow"))
        self.label.setText(_translate("Setup", "HỆ THỐNG ĐO LƯỜNG CÁC CHỈ SỐ SINH TỒN HỖ TRỢ BỆNH NHÂN SỐT XUẤT HUYẾT"))
        self.label_2.setText(_translate("Setup", "CẤU HÌNH THIẾT BỊ"))
        self.groupBox.setTitle(_translate("Setup", "Thiết bị sử dụng"))
        self.device.setItemText(0, _translate("Setup", "USB"))
        self.device.setItemText(1, _translate("Setup", "Device1"))
        self.device.setItemText(2, _translate("Setup", "Device2"))
        self.device.setItemText(3, _translate("Setup", "Device3"))
        self.check1.setText(_translate("Setup", "Kiểm tra hoạt động"))
        self.button2.setTitle(_translate("Setup", "Cổng đầu vào thiết bị"))
        self.input.setItemText(0, _translate("Setup", "ai0"))
        self.input.setItemText(1, _translate("Setup", "ai1"))
        self.input.setItemText(2, _translate("Setup", "ai2"))
        self.input.setItemText(3, _translate("Setup", "ai3"))
        self.check2.setText(_translate("Setup", "Kiểm tra hoạt động"))

    def checkfunction(self):
        if self.check1.isChecked():
            print('sucess')
        else:
            print('fail')

        if self.check2.isChecked():
            print('succ')
        else:
            print('fail')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Setup = QtWidgets.QMainWindow()
    ui = Ui_Setup()
    ui.setupUi(Setup)
    Setup.show()
    sys.exit(app.exec_())
