# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.controller.setup_controller import *


class Ui_Setup(object):
    def setupUi(self, Setup):
        Setup.setObjectName("Setup")
        Setup.resize(680, 500)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        Setup.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Setup)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 50, 511, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 130, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 170, 191, 151))
        self.groupBox.setObjectName("groupBox")

        # list Devices
        self.device = QtWidgets.QComboBox(self.groupBox)
        self.device.setGeometry(QtCore.QRect(10, 30, 121, 22))
        self.device.setObjectName("device")

        # button check device
        self.button_check_devices = QtWidgets.QPushButton(self.groupBox)
        self.button_check_devices.setGeometry(QtCore.QRect(10, 80, 121, 28))
        self.button_check_devices.setObjectName("check1")

        # button check
        self.button2 = QtWidgets.QGroupBox(self.centralwidget)
        self.button2.setGeometry(QtCore.QRect(400, 170, 191, 151))
        self.button2.setObjectName("button2")

        self.combobox_ports = QtWidgets.QComboBox(self.button2)
        self.combobox_ports.setGeometry(QtCore.QRect(10, 30, 121, 22))
        self.combobox_ports.setObjectName("input")

        # button check port
        self.button_check_port = QtWidgets.QPushButton(self.button2)
        self.button_check_port.setGeometry(QtCore.QRect(10, 80, 121, 28))
        self.button_check_port.setObjectName("check2")
        Setup.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(Setup)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 23))
        self.menubar.setObjectName("menubar")
        Setup.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Setup)
        self.statusbar.setObjectName("statusbar")
        Setup.setStatusBar(self.statusbar)

        # Thiết lập
        self.retranslateUi(Setup)
        self.setup_list_device()
        self.setup_list_port()

        QtCore.QMetaObject.connectSlotsByName(Setup)

        # kiem tra trang thai
        self.button_check_devices.clicked.connect(self.check_device_active_event)
        self.button_check_port.clicked.connect(self.check_port_working_event)

    def retranslateUi(self, Setup):
        name_software = "Phần mềm theo dõi bệnh nhân sốt xuất huyết"
        name_software_title = "HỆ THỐNG ĐO LƯỜNG CÁC CHỈ SỐ SINH TỒN HỖ TRỢ BỆNH NHÂN SỐT XUẤT HUYẾT"

        # config name software
        _translate = QtCore.QCoreApplication.translate
        Setup.setWindowTitle(_translate("Setup", name_software))
        self.label.setText(_translate("Setup", name_software_title))

        self.label_2.setText(_translate("Setup", "CẤU HÌNH THIẾT BỊ"))
        self.groupBox.setTitle(_translate("Setup", "Thiết bị sử dụng"))

        # button check Device
        self.button_check_devices.setText(_translate("Setup", "Kiểm tra hoạt động"))

        # combo box list ports
        self.button2.setTitle(_translate("Setup", "Cổng đầu vào thiết bị"))

        # button check ports
        self.button_check_port.setText(_translate("Setup", "Kiểm tra hoạt động"))

    def setup_list_device(self, data=['Dev1', 'Dev2']):
        set_item_for_commbo_box(data, self.device)
        pass

    def setup_list_port(self, name_device='Dev1'):
        data = ['ai0', 'ai1', 'ai2']
        concatenated_data = map(lambda ele: name_device + '/' + ele, data)
        set_item_for_commbo_box(concatenated_data, self.combobox_ports)

    def check_device_active_event(self):
        if self.button_check_devices.isChecked():
            print('sucess')
        else:
            print('fail')

    def check_port_working_event(self):
        if self.button_check_port.isChecked():
            print('succ')
        else:
            print('fail')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Setup = QtWidgets.QMainWindow()
    ui = Ui_Setup()
    ui.setupUi(Setup)

    # config app
    from src.controller.setup_controller import *


    # set name soft ware
    # name_software_title = "HỆ THỐNG ĐO LƯỜNG CÁC CHỈ SỐ SINH TỒN HỖ TRỢ BỆNH NHÂN SỐT XUẤT HUYẾT"

    # name_software(ui.label, name_software_title)

    def set_list_device():
        pass


    def set_list_device():
        pass


    def check_device_working():
        pass


    def check_port_working():
        pass


    Setup.show()
    sys.exit(app.exec_())
